// KeywordList.dart

class KeywordList {
  // Define the keyword combinations as a list of lists
  final List<List<String>> _keywordCombinations = [
    // Player One
    ["Player One", "Miss"],
    ["Player One", "Made", "1"],
    ["Player One", "Made", "2"],
    ["Player One", "Made", "3"],
    ["Player One", "Rebound", "Offensive"],
    ["Player One", "Rebound", "Defense"],
    ["Player One", "Foul"],
    ["Player One", "Turnover"],
    ["Player One", "Assist"],
    ["Player One", "Steal"],
    ["Player One", "Block"],

    // Player Two
    ["Player Two", "Miss"],
    ["Player Two", "Made", "1"],
    ["Player Two", "Made", "2"],
    ["Player Two", "Made", "3"],
    ["Player Two", "Rebound", "Offensive"],
    ["Player Two", "Rebound", "Defense"],
    ["Player Two", "Foul"],
    ["Player Two", "Turnover"],
    ["Player Two", "Assist"],
    ["Player Two", "Steal"],
    ["Player Two", "Block"],

    // Player Three
    ["Player Three", "Miss"],
    ["Player Three", "Made", "1"],
    ["Player Three", "Made", "2"],
    ["Player Three", "Made", "3"],
    ["Player Three", "Rebound", "Offensive"],
    ["Player Three", "Rebound", "Defense"],
    ["Player Three", "Foul"],
    ["Player Three", "Turnover"],
    ["Player Three", "Assist"],
    ["Player Three", "Steal"],
    ["Player Three", "Block"],

    // Player Four
    ["Player Four", "Miss"],
    ["Player Four", "Made", "1"],
    ["Player Four", "Made", "2"],
    ["Player Four", "Made", "3"],
    ["Player Four", "Rebound", "Offensive"],
    ["Player Four", "Rebound", "Defense"],
    ["Player Four", "Foul"],
    ["Player Four", "Turnover"],
    ["Player Four", "Assist"],
    ["Player Four", "Steal"],
    ["Player Four", "Block"],

    // Player Five
    ["Player Five", "Miss"],
    ["Player Five", "Made", "1"],
    ["Player Five", "Made", "2"],
    ["Player Five", "Made", "3"],
    ["Player Five", "Rebound", "Offensive"],
    ["Player Five", "Rebound", "Defense"],
    ["Player Five", "Foul"],
    ["Player Five", "Turnover"],
    ["Player Five", "Assist"],
    ["Player Five", "Steal"],
    ["Player Five", "Block"],

    // Player Six
    ["Player Six", "Miss"],
    ["Player Six", "Made", "1"],
    ["Player Six", "Made", "2"],
    ["Player Six", "Made", "3"],
    ["Player Six", "Rebound", "Offensive"],
    ["Player Six", "Rebound", "Defense"],
    ["Player Six", "Foul"],
    ["Player Six", "Turnover"],
    ["Player Six", "Assist"],
    ["Player Six", "Steal"],
    ["Player Six", "Block"],

    // Player Seven
    ["Player Seven", "Miss"],
    ["Player Seven", "Made", "1"],
    ["Player Seven", "Made", "2"],
    ["Player Seven", "Made", "3"],
    ["Player Seven", "Rebound", "Offensive"],
    ["Player Seven", "Rebound", "Defense"],
    ["Player Seven", "Foul"],
    ["Player Seven", "Turnover"],
    ["Player Seven", "Assist"],
    ["Player Seven", "Steal"],
    ["Player Seven", "Block"],

    // Player Eight
    ["Player Eight", "Miss"],
    ["Player Eight", "Made", "1"],
    ["Player Eight", "Made", "2"],
    ["Player Eight", "Made", "3"],
    ["Player Eight", "Rebound", "Offensive"],
    ["Player Eight", "Rebound", "Defense"],
    ["Player Eight", "Foul"],
    ["Player Eight", "Turnover"],
    ["Player Eight", "Assist"],
    ["Player Eight", "Steal"],
    ["Player Eight", "Block"],

    // Player Nine
    ["Player Nine", "Miss"],
    ["Player Nine", "Made", "1"],
    ["Player Nine", "Made", "2"],
    ["Player Nine", "Made", "3"],
    ["Player Nine", "Rebound", "Offensive"],
    ["Player Nine", "Rebound", "Defense"],
    ["Player Nine", "Foul"],
    ["Player Nine", "Turnover"],
    ["Player Nine", "Assist"],
    ["Player Nine", "Steal"],
    ["Player Nine", "Block"],

    // Player Ten
    ["Player Ten", "Miss"],
    ["Player Ten", "Made", "1"],
    ["Player Ten", "Made", "2"],
    ["Player Ten", "Made", "3"],
    ["Player Ten", "Rebound", "Offensive"],
    ["Player Ten", "Rebound", "Defense"],
    ["Player Ten", "Foul"],
    ["Player Ten", "Turnover"],
    ["Player Ten", "Assist"],
    ["Player Ten", "Steal"],
    ["Player Ten", "Block"],

    // Player Eleven
    ["Player Eleven", "Miss"],
    ["Player Eleven", "Made", "1"],
    ["Player Eleven", "Made", "2"],
    ["Player Eleven", "Made", "3"],
    ["Player Eleven", "Rebound", "Offensive"],
    ["Player Eleven", "Rebound", "Defense"],
    ["Player Eleven", "Foul"],
    ["Player Eleven", "Turnover"],
    ["Player Eleven", "Assist"],
    ["Player Eleven", "Steal"],
    ["Player Eleven", "Block"],

    // Player Twelve
    ["Player Twelve", "Miss"],
    ["Player Twelve", "Made", "1"],
    ["Player Twelve", "Made", "2"],
    ["Player Twelve", "Made", "3"],
    ["Player Twelve", "Rebound", "Offensive"],
    ["Player Twelve", "Rebound", "Defense"],
    ["Player Twelve", "Foul"],
    ["Player Twelve", "Turnover"],
    ["Player Twelve", "Assist"],
    ["Player Twelve", "Steal"],
    ["Player Twelve", "Block"],

    // Player Thirteen
    ["Player Thirteen", "Miss"],
    ["Player Thirteen", "Made", "1"],
    ["Player Thirteen", "Made", "2"],
    ["Player Thirteen", "Made", "3"],
    ["Player Thirteen", "Rebound", "Offensive"],
    ["Player Thirteen", "Rebound", "Defense"],
    ["Player Thirteen", "Foul"],
    ["Player Thirteen", "Turnover"],
    ["Player Thirteen", "Assist"],
    ["Player Thirteen", "Steal"],
    ["Player Thirteen", "Block"],

    // Player Fourteen
    ["Player Fourteen", "Miss"],
    ["Player Fourteen", "Made", "1"],
    ["Player Fourteen", "Made", "2"],
    ["Player Fourteen", "Made", "3"],
    ["Player Fourteen", "Rebound", "Offensive"],
    ["Player Fourteen", "Rebound", "Defense"],
    ["Player Fourteen", "Foul"],
    ["Player Fourteen", "Turnover"],
    ["Player Fourteen", "Assist"],
    ["Player Fourteen", "Steal"],
    ["Player Fourteen", "Block"],

    // Player Fifteen
    ["Player Fifteen", "Miss"],
    ["Player Fifteen", "Made", "1"],
    ["Player Fifteen", "Made", "2"],
    ["Player Fifteen", "Made", "3"],
    ["Player Fifteen", "Rebound", "Offensive"],
    ["Player Fifteen", "Rebound", "Defense"],
    ["Player Fifteen", "Foul"],
    ["Player Fifteen", "Turnover"],
    ["Player Fifteen", "Assist"],
    ["Player Fifteen", "Steal"],
    ["Player Fifteen", "Block"],

    // Player Sixteen
    ["Player Sixteen", "Miss"],
    ["Player Sixteen", "Made", "1"],
    ["Player Sixteen", "Made", "2"],
    ["Player Sixteen", "Made", "3"],
    ["Player Sixteen", "Rebound", "Offensive"],
    ["Player Sixteen", "Rebound", "Defense"],
    ["Player Sixteen", "Foul"],
    ["Player Sixteen", "Turnover"],
    ["Player Sixteen", "Assist"],
    ["Player Sixteen", "Steal"],
    ["Player Sixteen", "Block"],

    // Player Seventeen
    ["Player Seventeen", "Miss"],
    ["Player Seventeen", "Made", "1"],
    ["Player Seventeen", "Made", "2"],
    ["Player Seventeen", "Made", "3"],
    ["Player Seventeen", "Rebound", "Offensive"],
    ["Player Seventeen", "Rebound", "Defense"],
    ["Player Seventeen", "Foul"],
    ["Player Seventeen", "Turnover"],
    ["Player Seventeen", "Assist"],
    ["Player Seventeen", "Steal"],
    ["Player Seventeen", "Block"],

    // Player Eighteen
    ["Player Eighteen", "Miss"],
    ["Player Eighteen", "Made", "1"],
    ["Player Eighteen", "Made", "2"],
    ["Player Eighteen", "Made", "3"],
    ["Player Eighteen", "Rebound", "Offensive"],
    ["Player Eighteen", "Rebound", "Defense"],
    ["Player Eighteen", "Foul"],
    ["Player Eighteen", "Turnover"],
    ["Player Eighteen", "Assist"],
    ["Player Eighteen", "Steal"],
    ["Player Eighteen", "Block"],

    // Player Nineteen
    ["Player Nineteen", "Miss"],
    ["Player Nineteen", "Made", "1"],
    ["Player Nineteen", "Made", "2"],
    ["Player Nineteen", "Made", "3"],
    ["Player Nineteen", "Rebound", "Offensive"],
    ["Player Nineteen", "Rebound", "Defense"],
    ["Player Nineteen", "Foul"],
    ["Player Nineteen", "Turnover"],
    ["Player Nineteen", "Assist"],
    ["Player Nineteen", "Steal"],
    ["Player Nineteen", "Block"],

    // Player Twenty
    ["Player Twenty", "Miss"],
    ["Player Twenty", "Made", "1"],
    ["Player Twenty", "Made", "2"],
    ["Player Twenty", "Made", "3"],
    ["Player Twenty", "Rebound", "Offensive"],
    ["Player Twenty", "Rebound", "Defense"],
    ["Player Twenty", "Foul"],
    ["Player Twenty", "Turnover"],
    ["Player Twenty", "Assist"],
    ["Player Twenty", "Steal"],
    ["Player Twenty", "Block"],

    // Player Twenty-One
    ["Player Twenty-One", "Miss"],
    ["Player Twenty-One", "Made", "1"],
    ["Player Twenty-One", "Made", "2"],
    ["Player Twenty-One", "Made", "3"],
    ["Player Twenty-One", "Rebound", "Offensive"],
    ["Player Twenty-One", "Rebound", "Defense"],
    ["Player Twenty-One", "Foul"],
    ["Player Twenty-One", "Turnover"],
    ["Player Twenty-One", "Assist"],
    ["Player Twenty-One", "Steal"],
    ["Player Twenty-One", "Block"],

    // Player Twenty-Two
    ["Player Twenty-Two", "Miss"],
    ["Player Twenty-Two", "Made", "1"],
    ["Player Twenty-Two", "Made", "2"],
    ["Player Twenty-Two", "Made", "3"],
    ["Player Twenty-Two", "Rebound", "Offensive"],
    ["Player Twenty-Two", "Rebound", "Defense"],
    ["Player Twenty-Two", "Foul"],
    ["Player Twenty-Two", "Turnover"],
    ["Player Twenty-Two", "Assist"],
    ["Player Twenty-Two", "Steal"],
    ["Player Twenty-Two", "Block"],

    // Player Twenty-Three
    ["Player Twenty-Three", "Miss"],
    ["Player Twenty-Three", "Made", "1"],
    ["Player Twenty-Three", "Made", "2"],
    ["Player Twenty-Three", "Made", "3"],
    ["Player Twenty-Three", "Rebound", "Offensive"],
    ["Player Twenty-Three", "Rebound", "Defense"],
    ["Player Twenty-Three", "Foul"],
    ["Player Twenty-Three", "Turnover"],
    ["Player Twenty-Three", "Assist"],
    ["Player Twenty-Three", "Steal"],
    ["Player Twenty-Three", "Block"],

    // Player Twenty-Four
    ["Player Twenty-Four", "Miss"],
    ["Player Twenty-Four", "Made", "1"],
    ["Player Twenty-Four", "Made", "2"],
    ["Player Twenty-Four", "Made", "3"],
    ["Player Twenty-Four", "Rebound", "Offensive"],
    ["Player Twenty-Four", "Rebound", "Defense"],
    ["Player Twenty-Four", "Foul"],
    ["Player Twenty-Four", "Turnover"],
    ["Player Twenty-Four", "Assist"],
    ["Player Twenty-Four", "Steal"],
    ["Player Twenty-Four", "Block"],

    // Player Twenty-Five
    ["Player Twenty-Five", "Miss"],
    ["Player Twenty-Five", "Made", "1"],
    ["Player Twenty-Five", "Made", "2"],
    ["Player Twenty-Five", "Made", "3"],
    ["Player Twenty-Five", "Rebound", "Offensive"],
    ["Player Twenty-Five", "Rebound", "Defense"],
    ["Player Twenty-Five", "Foul"],
    ["Player Twenty-Five", "Turnover"],
    ["Player Twenty-Five", "Assist"],
    ["Player Twenty-Five", "Steal"],
    ["Player Twenty-Five", "Block"],

    // Player Twenty-Six
    ["Player Twenty-Six", "Miss"],
    ["Player Twenty-Six", "Made", "1"],
    ["Player Twenty-Six", "Made", "2"],
    ["Player Twenty-Six", "Made", "3"],
    ["Player Twenty-Six", "Rebound", "Offensive"],
    ["Player Twenty-Six", "Rebound", "Defense"],
    ["Player Twenty-Six", "Foul"],
    ["Player Twenty-Six", "Turnover"],
    ["Player Twenty-Six", "Assist"],
    ["Player Twenty-Six", "Steal"],
    ["Player Twenty-Six", "Block"],

    // Player Twenty-Seven
    ["Player Twenty-Seven", "Miss"],
    ["Player Twenty-Seven", "Made", "1"],
    ["Player Twenty-Seven", "Made", "2"],
    ["Player Twenty-Seven", "Made", "3"],
    ["Player Twenty-Seven", "Rebound", "Offensive"],
    ["Player Twenty-Seven", "Rebound", "Defense"],
    ["Player Twenty-Seven", "Foul"],
    ["Player Twenty-Seven", "Turnover"],
    ["Player Twenty-Seven", "Assist"],
    ["Player Twenty-Seven", "Steal"],
    ["Player Twenty-Seven", "Block"],

    // Player Twenty-Eight
    ["Player Twenty-Eight", "Miss"],
    ["Player Twenty-Eight", "Made", "1"],
    ["Player Twenty-Eight", "Made", "2"],
    ["Player Twenty-Eight", "Made", "3"],
    ["Player Twenty-Eight", "Rebound", "Offensive"],
    ["Player Twenty-Eight", "Rebound", "Defense"],
    ["Player Twenty-Eight", "Foul"],
    ["Player Twenty-Eight", "Turnover"],
    ["Player Twenty-Eight", "Assist"],
    ["Player Twenty-Eight", "Steal"],
    ["Player Twenty-Eight", "Block"],

    // Player Twenty-Nine
    ["Player Twenty-Nine", "Miss"],
    ["Player Twenty-Nine", "Made", "1"],
    ["Player Twenty-Nine", "Made", "2"],
    ["Player Twenty-Nine", "Made", "3"],
    ["Player Twenty-Nine", "Rebound", "Offensive"],
    ["Player Twenty-Nine", "Rebound", "Defense"],
    ["Player Twenty-Nine", "Foul"],
    ["Player Twenty-Nine", "Turnover"],
    ["Player Twenty-Nine", "Assist"],
    ["Player Twenty-Nine", "Steal"],
    ["Player Twenty-Nine", "Block"],

    // Player Thirty
    ["Player Thirty", "Miss"],
    ["Player Thirty", "Made", "1"],
    ["Player Thirty", "Made", "2"],
    ["Player Thirty", "Made", "3"],
    ["Player Thirty", "Rebound", "Offensive"],
    ["Player Thirty", "Rebound", "Defense"],
    ["Player Thirty", "Foul"],
    ["Player Thirty", "Turnover"],
    ["Player Thirty", "Assist"],
    ["Player Thirty", "Steal"],
    ["Player Thirty", "Block"],

    // Player Thirty-One
    ["Player Thirty-One", "Miss"],
    ["Player Thirty-One", "Made", "1"],
    ["Player Thirty-One", "Made", "2"],
    ["Player Thirty-One", "Made", "3"],
    ["Player Thirty-One", "Rebound", "Offensive"],
    ["Player Thirty-One", "Rebound", "Defense"],
    ["Player Thirty-One", "Foul"],
    ["Player Thirty-One", "Turnover"],
    ["Player Thirty-One", "Assist"],
    ["Player Thirty-One", "Steal"],
    ["Player Thirty-One", "Block"],

    // Player Thirty-Two
    ["Player Thirty-Two", "Miss"],
    ["Player Thirty-Two", "Made", "1"],
    ["Player Thirty-Two", "Made", "2"],
    ["Player Thirty-Two", "Made", "3"],
    ["Player Thirty-Two", "Rebound", "Offensive"],
    ["Player Thirty-Two", "Rebound", "Defense"],
    ["Player Thirty-Two", "Foul"],
    ["Player Thirty-Two", "Turnover"],
    ["Player Thirty-Two", "Assist"],
    ["Player Thirty-Two", "Steal"],
    ["Player Thirty-Two", "Block"],

    // Player Thirty-Three
    ["Player Thirty-Three", "Miss"],
    ["Player Thirty-Three", "Made", "1"],
    ["Player Thirty-Three", "Made", "2"],
    ["Player Thirty-Three", "Made", "3"],
    ["Player Thirty-Three", "Rebound", "Offensive"],
    ["Player Thirty-Three", "Rebound", "Defense"],
    ["Player Thirty-Three", "Foul"],
    ["Player Thirty-Three", "Turnover"],
    ["Player Thirty-Three", "Assist"],
    ["Player Thirty-Three", "Steal"],
    ["Player Thirty-Three", "Block"],

    // Player Thirty-Four
    ["Player Thirty-Four", "Miss"],
    ["Player Thirty-Four", "Made", "1"],
    ["Player Thirty-Four", "Made", "2"],
    ["Player Thirty-Four", "Made", "3"],
    ["Player Thirty-Four", "Rebound", "Offensive"],
    ["Player Thirty-Four", "Rebound", "Defense"],
    ["Player Thirty-Four", "Foul"],
    ["Player Thirty-Four", "Turnover"],
    ["Player Thirty-Four", "Assist"],
    ["Player Thirty-Four", "Steal"],
    ["Player Thirty-Four", "Block"],

    // Player Thirty-Five
    ["Player Thirty-Five", "Miss"],
    ["Player Thirty-Five", "Made", "1"],
    ["Player Thirty-Five", "Made", "2"],
    ["Player Thirty-Five", "Made", "3"],
    ["Player Thirty-Five", "Rebound", "Offensive"],
    ["Player Thirty-Five", "Rebound", "Defense"],
    ["Player Thirty-Five", "Foul"],
    ["Player Thirty-Five", "Turnover"],
    ["Player Thirty-Five", "Assist"],
    ["Player Thirty-Five", "Steal"],
    ["Player Thirty-Five", "Block"],

    // Player Thirty-Six
    ["Player Thirty-Six", "Miss"],
    ["Player Thirty-Six", "Made", "1"],
    ["Player Thirty-Six", "Made", "2"],
    ["Player Thirty-Six", "Made", "3"],
    ["Player Thirty-Six", "Rebound", "Offensive"],
    ["Player Thirty-Six", "Rebound", "Defense"],
    ["Player Thirty-Six", "Foul"],
    ["Player Thirty-Six", "Turnover"],
    ["Player Thirty-Six", "Assist"],
    ["Player Thirty-Six", "Steal"],
    ["Player Thirty-Six", "Block"],

    // Player Thirty-Seven
    ["Player Thirty-Seven", "Miss"],
    ["Player Thirty-Seven", "Made", "1"],
    ["Player Thirty-Seven", "Made", "2"],
    ["Player Thirty-Seven", "Made", "3"],
    ["Player Thirty-Seven", "Rebound", "Offensive"],
    ["Player Thirty-Seven", "Rebound", "Defense"],
    ["Player Thirty-Seven", "Foul"],
    ["Player Thirty-Seven", "Turnover"],
    ["Player Thirty-Seven", "Assist"],
    ["Player Thirty-Seven", "Steal"],
    ["Player Thirty-Seven", "Block"],

    // Player Thirty-Eight
    ["Player Thirty-Eight", "Miss"],
    ["Player Thirty-Eight", "Made", "1"],
    ["Player Thirty-Eight", "Made", "2"],
    ["Player Thirty-Eight", "Made", "3"],
    ["Player Thirty-Eight", "Rebound", "Offensive"],
    ["Player Thirty-Eight", "Rebound", "Defense"],
    ["Player Thirty-Eight", "Foul"],
    ["Player Thirty-Eight", "Turnover"],
    ["Player Thirty-Eight", "Assist"],
    ["Player Thirty-Eight", "Steal"],
    ["Player Thirty-Eight", "Block"],

    // Player Thirty-Nine
    ["Player Thirty-Nine", "Miss"],
    ["Player Thirty-Nine", "Made", "1"],
    ["Player Thirty-Nine", "Made", "2"],
    ["Player Thirty-Nine", "Made", "3"],
    ["Player Thirty-Nine", "Rebound", "Offensive"],
    ["Player Thirty-Nine", "Rebound", "Defense"],
    ["Player Thirty-Nine", "Foul"],
    ["Player Thirty-Nine", "Turnover"],
    ["Player Thirty-Nine", "Assist"],
    ["Player Thirty-Nine", "Steal"],
    ["Player Thirty-Nine", "Block"],

    // Player Forty
    ["Player Forty", "Miss"],
    ["Player Forty", "Made", "1"],
    ["Player Forty", "Made", "2"],
    ["Player Forty", "Made", "3"],
    ["Player Forty", "Rebound", "Offensive"],
    ["Player Forty", "Rebound", "Defense"],
    ["Player Forty", "Foul"],
    ["Player Forty", "Turnover"],
    ["Player Forty", "Assist"],
    ["Player Forty", "Steal"],
    ["Player Forty", "Block"],

    // Player Forty-One
    ["Player Forty-One", "Miss"],
    ["Player Forty-One", "Made", "1"],
    ["Player Forty-One", "Made", "2"],
    ["Player Forty-One", "Made", "3"],
    ["Player Forty-One", "Rebound", "Offensive"],
    ["Player Forty-One", "Rebound", "Defense"],
    ["Player Forty-One", "Foul"],
    ["Player Forty-One", "Turnover"],
    ["Player Forty-One", "Assist"],
    ["Player Forty-One", "Steal"],
    ["Player Forty-One", "Block"],

    // Player Forty-Two
    ["Player Forty-Two", "Miss"],
    ["Player Forty-Two", "Made", "1"],
    ["Player Forty-Two", "Made", "2"],
    ["Player Forty-Two", "Made", "3"],
    ["Player Forty-Two", "Rebound", "Offensive"],
    ["Player Forty-Two", "Rebound", "Defense"],
    ["Player Forty-Two", "Foul"],
    ["Player Forty-Two", "Turnover"],
    ["Player Forty-Two", "Assist"],
    ["Player Forty-Two", "Steal"],
    ["Player Forty-Two", "Block"],

    // Player Forty-Three
    ["Player Forty-Three", "Miss"],
    ["Player Forty-Three", "Made", "1"],
    ["Player Forty-Three", "Made", "2"],
    ["Player Forty-Three", "Made", "3"],
    ["Player Forty-Three", "Rebound", "Offensive"],
    ["Player Forty-Three", "Rebound", "Defense"],
    ["Player Forty-Three", "Foul"],
    ["Player Forty-Three", "Turnover"],
    ["Player Forty-Three", "Assist"],
    ["Player Forty-Three", "Steal"],
    ["Player Forty-Three", "Block"],

    // Player Forty-Four
    ["Player Forty-Four", "Miss"],
    ["Player Forty-Four", "Made", "1"],
    ["Player Forty-Four", "Made", "2"],
    ["Player Forty-Four", "Made", "3"],
    ["Player Forty-Four", "Rebound", "Offensive"],
    ["Player Forty-Four", "Rebound", "Defense"],
    ["Player Forty-Four", "Foul"],
    ["Player Forty-Four", "Turnover"],
    ["Player Forty-Four", "Assist"],
    ["Player Forty-Four", "Steal"],
    ["Player Forty-Four", "Block"],

    // Player Forty-Five
    ["Player Forty-Five", "Miss"],
    ["Player Forty-Five", "Made", "1"],
    ["Player Forty-Five", "Made", "2"],
    ["Player Forty-Five", "Made", "3"],
    ["Player Forty-Five", "Rebound", "Offensive"],
    ["Player Forty-Five", "Rebound", "Defense"],
    ["Player Forty-Five", "Foul"],
    ["Player Forty-Five", "Turnover"],
    ["Player Forty-Five", "Assist"],
    ["Player Forty-Five", "Steal"],
    ["Player Forty-Five", "Block"],

    // Player Forty-Six
    ["Player Forty-Six", "Miss"],
    ["Player Forty-Six", "Made", "1"],
    ["Player Forty-Six", "Made", "2"],
    ["Player Forty-Six", "Made", "3"],
    ["Player Forty-Six", "Rebound", "Offensive"],
    ["Player Forty-Six", "Rebound", "Defense"],
    ["Player Forty-Six", "Foul"],
    ["Player Forty-Six", "Turnover"],
    ["Player Forty-Six", "Assist"],
    ["Player Forty-Six", "Steal"],
    ["Player Forty-Six", "Block"],

    // Player Forty-Seven
    ["Player Forty-Seven", "Miss"],
    ["Player Forty-Seven", "Made", "1"],
    ["Player Forty-Seven", "Made", "2"],
    ["Player Forty-Seven", "Made", "3"],
    ["Player Forty-Seven", "Rebound", "Offensive"],
    ["Player Forty-Seven", "Rebound", "Defense"],
    ["Player Forty-Seven", "Foul"],
    ["Player Forty-Seven", "Turnover"],
    ["Player Forty-Seven", "Assist"],
    ["Player Forty-Seven", "Steal"],
    ["Player Forty-Seven", "Block"],

    // Player Forty-Eight
    ["Player Forty-Eight", "Miss"],
    ["Player Forty-Eight", "Made", "1"],
    ["Player Forty-Eight", "Made", "2"],
    ["Player Forty-Eight", "Made", "3"],
    ["Player Forty-Eight", "Rebound", "Offensive"],
    ["Player Forty-Eight", "Rebound", "Defense"],
    ["Player Forty-Eight", "Foul"],
    ["Player Forty-Eight", "Turnover"],
    ["Player Forty-Eight", "Assist"],
    ["Player Forty-Eight", "Steal"],
    ["Player Forty-Eight", "Block"],

    // Player Forty-Nine
    ["Player Forty-Nine", "Miss"],
    ["Player Forty-Nine", "Made", "1"],
    ["Player Forty-Nine", "Made", "2"],
    ["Player Forty-Nine", "Made", "3"],
    ["Player Forty-Nine", "Rebound", "Offensive"],
    ["Player Forty-Nine", "Rebound", "Defense"],
    ["Player Forty-Nine", "Foul"],
    ["Player Forty-Nine", "Turnover"],
    ["Player Forty-Nine", "Assist"],
    ["Player Forty-Nine", "Steal"],
    ["Player Forty-Nine", "Block"],

    // Player Fifty
    ["Player Fifty", "Miss"],
    ["Player Fifty", "Made", "1"],
    ["Player Fifty", "Made", "2"],
    ["Player Fifty", "Made", "3"],
    ["Player Fifty", "Rebound", "Offensive"],
    ["Player Fifty", "Rebound", "Defense"],
    ["Player Fifty", "Foul"],
    ["Player Fifty", "Turnover"],
    ["Player Fifty", "Assist"],
    ["Player Fifty", "Steal"],
    ["Player Fifty", "Block"]
  ];

  // Method to check if a given array matches any keyword combination
  bool matches(List<String> dynamicArray) {
    return _keywordCombinations
        .any((combination) => _listsEqual(combination, dynamicArray));
  }

  // Helper method to compare two lists for equality
  bool _listsEqual(List<String> list1, List<String> list2) {
    if (list1.length != list2.length) return false;
    for (int i = 0; i < list1.length; i++) {
      if (list1[i] != list2[i]) return false;
    }
    return true;
  }
}
